env:
  global:
    - secure: LFLXKXr1nFmccFp3fNCW53tBofALGrC6LBtX3TSpx607JvQ+qS4ERjeTyHnrXNVbe1AClQ8jQETM8YlyQaxbl+OreiXZ4yZbpDGud+vz8EsZU+3wrXDUl8s9B96WGtj0biowHQubPFh/+NdDzBkqnn9TjDJIwbG8l1rvyimXmrA=
    - ElfUtilsVersion=0.163
os:
  - linux
  - osx
language: rust
rust:
  - nightly
  - beta
  - stable
sudo: false
branches:
  only:
    - master
cache:
  directories:
    - $HOME/elfutils-$ElfUtilsVersion
script:
  - curl -sSL https://github.com/maidsafe/QA/raw/master/Bash%20Scripts/Travis/build_and_run_tests.sh | bash
after_success:
  - curl -sSL https://github.com/maidsafe/QA/raw/master/Bash%20Scripts/Travis/after_success.sh | bash
