[package]
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "A key-value store limited by size or time, allowing accumulation of multiple values under a single key."
documentation = "http://maidsafe.net/accumulator/latest"
homepage = "http://maidsafe.net"
license = "GPL-3.0"
name = "accumulator"
readme = "README.md"
repository = "https://github.com/maidsafe/accumulator"
version = "0.1.3"

[dependencies]
log = "~0.3.5"
lru_time_cache = "~0.2.6"
time = "~0.1.34"

[dev-dependencies]
rand = "~0.3.13"
