[package]
name = "accumulator"
version = "0.1.3"
authors = ["MaidSafe Developers <dev@maidsafe.net>"]
description = "A key-value store limited by size or time, allowing accumulation of multiple values under a single key."
documentation = "http://maidsafe.net/accumulator/latest"
repository = "https://github.com/maidsafe/accumulator"
readme = "README.md"
license = "GPL-3.0"
homepage = "http://maidsafe.net"

[dependencies]
# ---- Non-MaidSafe -----
log = "~0.3.3"
time = "~0.1.34"

# ---- MaidSafe ------
lru_time_cache = "~0.2.4"

[dev-dependencies]
rand = "~0.3.12"
